### ISSUE TITLE
Species support

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#110]
Tasks:

- [x] determine and implement a representation for aliasing species and storing charge information
- [x] add support for parsing species in tdbs, modifying tdb parsing element parsing to match the above
- [ ] use species in the model (including calculating charge?)
- [ ] add charge balance as a constraint in the solver class

**Comment by richardotis** [comment]
The first two tasks are done now, right?

**Comment by richardotis** [comment]
Opinions (open to discussion) on how users manipulate species entries in Models:
1. All element/species strings entered in the `comps` should be internally promoted to `Species` objects (or a new `core` object if we want to enforce separation between `core` and `io`; alternatively we promote `Species` to a top-level object (TLO)). All components in the constituent arrays of `Database`s should also be promoted to objects.
2. Following (1), string-based comparison of components should go away everywhere. This may require Cythonization of `Species` (another point in favor of promotion to TLO) since string-based comparison of species names is in the hot path in several places.
3a. If only pure elements are specified in `comps`, all species which can be formed from the set of active elements should be entered.
3b. If at least one species is specified, no additional species should be automatically entered, but the corresponding pure elements (if not specified) should be automatically entered.
3c. We should also support "negation notation" for species where a user can write `'~CO2` or similar, and the system will ensure that the species is suspended, even if it would be automatically entered. I can also imagine supporting this for pure elements, so you could enter a species without a corresponding pure element, but how this feature would interact with 3a and 3b is unclear.

I am not really happy with the solution proposed in 3a-c; hoping we can come up with something better.

**Comment by bocklund** [comment]
What don't you like about 3? 3c might be kind of clumsy, but a and b seem like reasonable defaults. Assume all the species are active unless otherwise specified.

**Comment by richardotis** [comment]
This is just a situation where it seems like TC's stateful workspaces allow a more elegant expression of user intent.

With some examples showing users how to apply `set` operations to `dbf.species` to enter exactly what they want, it's probably fine.

**Comment by bocklund** [comment]
OTOH, the method proposed in 3 means you never have to (interactively or programmatically) inspect the state or find where the state is set in a script/program.
