### ISSUE TITLE
Add option in eqplot to turn off tielines

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#125]

**Comment by akashgoel1197** [comment]
Hello Sir , I would like to work on this issue. Since I'm a beginner can you help me with this issue.
Sir my understanding of the issue is that i have to add and additional parameter in eqplot to turn off the tielines. If i am correct, can you tell me what should i name that parameter and should i set its default value to be true or false.

**Comment by bocklund** [comment]
Sorry for the delay, I thought I responded to this. 

Your understanding is correct. I think a keyword argument to `eqplot` in `pycalphad.plot.eqplot` simply called `tielines` would be appropriate. Since tielines are currently plotted by default, we should make the default for that argument be `True`.
