### ISSUE TITLE
Introduction/Installation/Getting Started documentation

### ISSUE THREAD

**Issue by amjokisaari** [pycalphad/pycalphad#126]
Various suggestions to improve the documentation for introduction/installation/getting started:

- The conda installation instructions work for Linux as well as Windows.  This could be slightly confusing for new users.

- May want to indicate that conda may install in root and that users may need to sudo chown -r <usr> /path/to/conda in order to actually create new conda environments

- May wish to include a note about the possible gmpy2 incompatibility (though that seems to be fixed in version 0.5.2)

- May wish to indicate that the stable version does not ship with tests, or add a test suite (to keep someone from wasting time looking for how to test...); or indicate that you should at least run all the examples

- May wish to indicate that the dask warning for v0.5.2 is going to dealt with

- Indicate to users that mpicc may not be appropriate; and to use standard gcc compiler (for example, MOOSE will default load moose-dev-gcc module; this should be module purged before using pycalphad)

- Include information as to whether pycalphad can/should run in parallel or not; and if so, how to do so

- May want to include information as to how long computations for the example problems take (give reasonable expectations for performance)

**Comment by richardotis** [comment]
Thanks for collecting these points.

@bocklund In light of this question of testing, should we revisit #50 ?

**Comment by bocklund** [comment]
I think the suggestion to run the examples in lieu of tests is sufficient. The tests are somewhat instructive (and can be improved in this area) and provide visual visual feedback.

My other feedback on these points:

1. Agree this should be updated to suggest conda for all platforms, especially in light of https://github.com/pycalphad/pycalphad/pull/124
2. These are more one-off issues and I'd argue that most installations for conda work out of the box. This might confuse users who are possibly newer to Python (or Windows users). 
3. IMO, doesn't make sense to clutter current docs with issues in previous versions.
4. See comment above. Should add suggestion at end of installation to run examples.
5. I'm on the fence about this. To me, a warning is a notification of possible bad things, but that it is handled properly. Same goes for the numpy warnings. But I could see how this could be confusing.
6. Same as (2) above. I would be happy to try pointing this out in the MOOSE docs, where relevant. 
7. Great suggestion. I think this deserves a short page on parallelism in pycalphad with dask
8. Also a good point.

So then my suggested actions in pycalphad are 

* Update installation to first suggest anaconda installation for all platforms. Also update the development mode, because conda-build is not well maintained for using development mode in environments. Suggested to use pip or `setup.py` in https://github.com/conda/conda-build/issues/1992
* Add page describing parallelism with dask
* Estimate of computation time in the examples (roughly ~1 minute accuracy)
* (Possible) mention which warnings are normal to see, including convergence failures. Where should this go?

**Comment by richardotis** [comment]
@bocklund I agree with all your suggested actions. Please open issues for each and tag as 0.6 milestone blockers as you see fit.
