### ISSUE TITLE
Question about POP files

### ISSUE THREAD

**Issue by saurabh02** [pycalphad/pycalphad#131]
Hello,

I was wondering if there's any module that's been developed to read .POP files?

Thank you
Saurabh

**Comment by bocklund** [comment]
Hi Saurabh,

I've put a little effort into this a few months ago. I think at that point I was successfully parsing POP files, but I didn't actually manage to format the parsed data into anything useful.

Can you fill me in a little on what you are trying to do? Maybe I can help.

Brandon

**Comment by saurabh02** [comment]
Hi Brandon,

Thanks for your response. The data from POP files may be useful to overlay a phase diagram as "experimental" data or "user input".

Did you manage to integrate that with pycalphad or elsewhere? I'm curious to know if there's a standard format for such files, and if not, is it possible to build a generally applicable parser. 

Saurabh

**Comment by bocklund** [comment]
It's not integrated anywhere, but you can see the modules (pyparsing module and POP keywords module) [here](https://github.com/bocklund/pycalphad-fitting/tree/tools/utils). It is indeed hard, but I think I've managed to cover many cases in what I have. I got side tracked before I was able to convert the parsed data into something meaningful.

For plotting points on the phase diagram, pycalphad does not currently have support for plotting data easily. [ESPEI](http://espei.org/en/latest/) is built on pycalphad and is designed for fitting phase diagrams. It has support for plotting phase equilibria and single phase formation and mixing data that are formatted as JSON files.

Since the plots returned from pycalphad's plotting functions are just matplotlib plots, you could add scatter points as you wish as well.

It's possible that converting POP files to ESPEI's JSON format will be on my radar again, but right now there's not a lot of demand for it AFAIK.

**Comment by bocklund** [comment]
@saurabh02 can I close this issue? Anything else to discuss? If you have any questions about what I sent you, feel free to send me an email at bocklund@psu.edu

**Comment by saurabh02** [comment]
@bocklund Thanks for the follow up! I tried using and playing around with your code with a few POP files I had and had marginal success. As you may know, POP files are quite customizable, i.e. there are several ways to represent commands and information. For example, "SET_ALTERNATE_CONDITION" could be represented by "SET_ALT_COND". 

The above command was also not supported. I was able to get around exception errors raised because of that, but I wasn't able to figure the same out the command "SET_START_VALUE T=928,X(Ti)=0.85". Let me know if you have any tips to offer regarding that.

Also, would you have any POP files that you could share that your parser would definitely work with?

Thanks!
Saurabh

**Comment by bocklund** [comment]
I'm happy to hear you were able to get it working at least a bit. From what I can see, it looks like I have all the keywords defined in `pop_keywords.py`, but if you look at the `_pop_grammar` function in `pop_conversion.py`, you can see that we don't ever handle those keywords. This is the case with SET_START_VALUE also. 

If you use the `POPCommand` class with the command you want in the `_pop_grammer`, it should handle all abbreviation automatically.

It's been awhile since I have looked at this, but I would be willing to revisit my effort if you have something specific to parse because this is useful for our work on [ESPEI](http://espei.org). Feel free to send me an email if you don't want to share your POP file publicly.

**Comment by saurabh02** [comment]
Great that this may be useful to as well. I have followed up over email, so I will close this issue here.
