### ISSUE TITLE
Releasing document is out of date

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#151]
Since direct pushing to master is now locked, the release process outlined in the document is incorrect, and will lead to subtle versioning errors due to mistakes in tagging.

**Comment by bocklund** [comment]
According to [the GH docs](https://help.github.com/articles/about-pull-request-merges/) it doesn't seem like there's a merge behavior that has what we want
- `Merge`creates a merge commit, so master would be ahead of develop so we would have to merge develop, pull master onto develop, then tag. Which is strange IMO
- `Squash and merge`squashes develop onto master, so their histories will be different
- `Rebase` claims to "update the committer information and create new commit SHAs" which makes the histories different.

Rebase is strange. I didn't know that it did that. Maybe it's new since they added the "bocklund committed with richardotis" PR merging on GH (similar to https://github.com/pycalphad/pycalphad/commit/e08b0d0caf20079049b104095bf191e11aabe605). I think the goal of that was to give credit to both the authors and the puller.

IMO then we should change the permission for writing to master by using `Restrict who can push to this branch` option and keep the current release instructions.

**Comment by richardotis** [comment]
OTOH the current configuration makes it really difficult to screw up master's history.

**Comment by richardotis** [comment]
(while making it quite easy to screw up the history on develop)

**Comment by bocklund** [comment]
Maybe it should be the reverse? "master" is just a "release" branch. A user/developer would likely never use master practically, otherwise they'd use the released package. "develop" is what a user/developer would actually use, so we should be trying to make that the one true history

**Comment by bocklund** [comment]
If something goes wrong in master, we should just be able to nuke it and replay from develop, since master always lags develop.

**Comment by richardotis** [comment]
Agreed. The configuration has been updated to once again allow direct pushes to master.
