### ISSUE TITLE
RecursionError: maximum recursion depth exceeded when running equilibrium

### ISSUE THREAD

**Issue by netwmr01** [pycalphad/pycalphad#194]
Python 3.6, pycalphad 0.7 ran into RecursionError.

Increase stack limit will segfault.

To reproduce, use the following notebook
https://notebooks.azure.com/anon-oxa74q/libraries/stack-limit-issue/html/statck-limit-issue.ipynb
```Python
ref_eq = equilibrium(dbf, comps, phases, {v.P: 101325, v.T: 1023, v.X('ZN'): 1})

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-6-7c7908689d1e> in <module>()
----> 1 ref_eq = equilibrium(dbf, comps, phases, {v.P: 101325, v.T: 1023, v.X('ZN'): 1})

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/equilibrium.py in equilibrium(dbf, comps, phases, conditions, output, model, verbose, broadcast, calc_opts, scheduler, parameters, **kwargs)
    266                 out = out.xreplace({undef: float(0)})
    267             cf, gf = build_functions(out, tuple([v.P, v.T] + site_fracs),
--> 268                                      parameters=param_symbols)
    269             hf = None
    270             if callable_dict.get(name, None) is None:

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/cache.py in wrapper(*args, **kwds)
    138                         stats[HITS] += 1
    139                         return result
--> 140                 result = user_function(*args, **kwds)
    141                 with lock:
    142                     root, = nonlocal_root

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/sympydiff_utils.py in build_functions(sympy_graph, variables, wrt, include_obj, include_grad, parameters)
    145         diffargs = (inp_nobroadcast, params)
    146         nobroadcast = dict(zip(variables+parameters, args_nobroadcast))
--> 147         sympy_graph_nobroadcast = sympy_graph.xreplace(nobroadcast)
    148         with CompileLock:
    149             grad_diffs = list(sympy_graph_nobroadcast.diff(nobroadcast[i]) for i in wrt)

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in xreplace(self, rule)
   1113 
   1114         """
-> 1115         value, _ = self._xreplace(rule)
   1116         return value
   1117 

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1134             args = tuple(args)
   1135             if changed:
-> 1136                 return self.func(*args), True
   1137         return self, False
   1138 

~/anaconda3_501/lib/python3.6/site-packages/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    136 
    137         if options.pop('evaluate', True):
--> 138             r = cls.eval(*newargs)
    139         else:
    140             r = None

~/anaconda3_501/lib/python3.6/site-packages/sympy/functions/elementary/piecewise.py in eval(cls, *_args)
    185                     x = free.pop()
    186                     try:
--> 187                         c = c.as_set().as_relational(x)
    188                     except NotImplementedError:
    189                         pass

~/anaconda3_501/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_set(self)
    144             reps = {}
    145             for r in self.atoms(Relational):
--> 146                 if periodicity(r, x) not in (0, None):
    147                     s = r._eval_as_set()
    148                     if s in (S.EmptySet, S.UniversalSet, S.Reals):

~/anaconda3_501/lib/python3.6/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    454         k, g = f.as_independent(symbol)
    455         if k is not S.Zero:
--> 456             return periodicity(g, symbol)
    457 
    458         period = _periodicity(g.args, symbol)

~/anaconda3_501/lib/python3.6/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    471     elif period is None:
    472         from sympy.solvers.decompogen import compogen
--> 473         g_s = decompogen(f, symbol)
    474         num_of_gs = len(g_s)
    475         if num_of_gs > 1:

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

... last 3 frames repeated, from the frame below ...

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59 

RecursionError: maximum recursion depth exceeded
```

**Comment by richardotis** [comment]
This is a known bug and will be fixed in the next release. For now, please downgrade to sympy 1.1.1

On Oct 31, 2018 8:52 AM, netwmr01 <notifications@github.com> wrote:

Python 3.6, pycalphad 0.7 ran into RecursionError.

Increase stack limit will segfault.

To reproduce, use the following notebook
https://notebooks.azure.com/anon-oxa74q/libraries/stack-limit-issue/html/statck-limit-issue.ipynb

ref_eq = equilibrium(dbf, comps, phases, {v.P: 101325, v.T: 1023, v.X('ZN'): 1})

---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
<ipython-input-6-7c7908689d1e> in <module>()
----> 1 ref_eq = equilibrium(dbf, comps, phases, {v.P: 101325, v.T: 1023, v.X('ZN'): 1})

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/equilibrium.py in equilibrium(dbf, comps, phases, conditions, output, model, verbose, broadcast, calc_opts, scheduler, parameters, **kwargs)
    266                 out = out.xreplace({undef: float(0)})
    267             cf, gf = build_functions(out, tuple([v.P, v.T] + site_fracs),
--> 268                                      parameters=param_symbols)
    269             hf = None
    270             if callable_dict.get(name, None) is None:

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/cache.py in wrapper(*args, **kwds)
    138                         stats[HITS] += 1
    139                         return result
--> 140                 result = user_function(*args, **kwds)
    141                 with lock:
    142                     root, = nonlocal_root

~/anaconda3_501/lib/python3.6/site-packages/pycalphad/core/sympydiff_utils.py in build_functions(sympy_graph, variables, wrt, include_obj, include_grad, parameters)
    145         diffargs = (inp_nobroadcast, params)
    146         nobroadcast = dict(zip(variables+parameters, args_nobroadcast))
--> 147         sympy_graph_nobroadcast = sympy_graph.xreplace(nobroadcast)
    148         with CompileLock:
    149             grad_diffs = list(sympy_graph_nobroadcast.diff(nobroadcast[i]) for i in wrt)

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in xreplace(self, rule)
   1113
   1114         """
-> 1115         value, _ = self._xreplace(rule)
   1116         return value
   1117

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1127             for a in self.args:
   1128                 try:
-> 1129                     a_xr = a._xreplace(rule)
   1130                     args.append(a_xr[0])
   1131                     changed |= a_xr[1]

~/anaconda3_501/lib/python3.6/site-packages/sympy/core/basic.py in _xreplace(self, rule)
   1134             args = tuple(args)
   1135             if changed:
-> 1136                 return self.func(*args), True
   1137         return self, False
   1138

~/anaconda3_501/lib/python3.6/site-packages/sympy/functions/elementary/piecewise.py in __new__(cls, *args, **options)
    136
    137         if options.pop('evaluate', True):
--> 138             r = cls.eval(*newargs)
    139         else:
    140             r = None

~/anaconda3_501/lib/python3.6/site-packages/sympy/functions/elementary/piecewise.py in eval(cls, *_args)
    185                     x = free.pop()
    186                     try:
--> 187                         c = c.as_set().as_relational(x)
    188                     except NotImplementedError:
    189                         pass

~/anaconda3_501/lib/python3.6/site-packages/sympy/logic/boolalg.py in as_set(self)
    144             reps = {}
    145             for r in self.atoms(Relational):
--> 146                 if periodicity(r, x) not in (0, None):
    147                     s = r._eval_as_set()
    148                     if s in (S.EmptySet, S.UniversalSet, S.Reals):

~/anaconda3_501/lib/python3.6/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    454         k, g = f.as_independent(symbol)
    455         if k is not S.Zero:
--> 456             return periodicity(g, symbol)
    457
    458         period = _periodicity(g.args, symbol)

~/anaconda3_501/lib/python3.6/site-packages/sympy/calculus/util.py in periodicity(f, symbol, check)
    471     elif period is None:
    472         from sympy.solvers.decompogen import compogen
--> 473         g_s = decompogen(f, symbol)
    474         num_of_gs = len(g_s)
    475         if num_of_gs > 1:

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59

... last 3 frames repeated, from the frame below ...

~/anaconda3_501/lib/python3.6/site-packages/sympy/solvers/decompogen.py in decompogen(f, symbol)
     55         f1 = f.subs(gens[0], symbol)
     56         f2 = gens[0]
---> 57         result += [f1] + decompogen(f2, symbol)
     58         return result
     59

RecursionError: maximum recursion depth exceeded

**Comment by netwmr01** [comment]
Thanks. 
May I suggest updating the "Installation Instructions", conda recipe, and adding a known issues list will be nice.
