### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#201]
A few non-blocking CI nice-to-haves:
- Remove obsolete Docker-related commands in `.travis.yml`
- Switch to a `conda-build`-based approach for installing pycalphad on CI. This will put the conda recipe through CI and create a single source of truth for dependencies.
- Refactor the tests to limit the total JIT time. Prefer recycled callables objects as much as possible.

**Comment by bocklund** [comment]
Also switching to pytest would be nice. Nose is not maintained and we don't use any advanced Nose features that should prevent us from switching

**Comment by bocklund** [comment]
Closed through #225 and #216 

Note that conda-build was determined not useful at this time because it significantly hurts the performance of the test suite (10 mins -> 20 mins according to #225).

With symengine support, CI run time is ~10 mins instead of ~40-50 mins on Travis, which precludes the need to refactor tests around minimizing JIT time for now.
