### ISSUE TITLE
cyipopt does not display IPOPT iterations

### ISSUE THREAD

**Issue by adkoele** [pycalphad/pycalphad#296]
I am using cyipopt throught the pycalphad package in Spyder. I would like to display the iteration progress from IPOPT. However, I am not able to change that option. I have talked to the cyipopt developers and they have indicated that it is a problem with the packages that are part of pycalphad. Therefore, I was wondering if you could help me. Is it possible to change the print level of IPOPT within the pycalphad package?

**Comment by bocklund** [comment]
Since there was already some discussion on this in https://github.com/mechmotum/cyipopt/issues/88, I [responded there](https://github.com/mechmotum/cyipopt/issues/88#issuecomment-755453608). I'm going to close the issue here so we can keep all the discussion consolidated in https://github.com/mechmotum/cyipopt/issues/88.
