### ISSUE TITLE
Influence of Model() in caluclate()

### ISSUE THREAD

**Issue by Ebert-Daniel** [pycalphad/pycalphad#305]
Hi all,
I'm studying pycalphad and I just realized that when I calculate the GM of all my phases and I plot it, I get wrong values if I used "Model()" some lines above of "calculate()" to get my GM expression .
When I skip the lines in which I called "Model()" then I get the expected curves.

summing up:
if I use:
Model(...).GM
and then,
calculate(...)
I get wrong GM curves of  the phases.
is this expected? what is the influence? Am I missing something?

Thank you for providing pycalphad
best wishes

**Comment by Ebert-Daniel** [comment]
more precisely, it happens when I use:
dbf.symbols = {}

**Comment by bocklund** [comment]
@Ebert-Daniel I'm not sure if you figured out your issue and meant to close the issue (if it's not resolved, you may re-open it).

If you load a database from a TDB file, the `FUNCTION` lines are entered into that Database's `symbols` dictionary, where the key is the name of the `FUNCTION` and the value is the expression (piecewise in temperature).

Setting `dbf.symbols` to an empty dictionary essentially "deletes" these `FUNCTION` definitions from your Database object. 

The `dbf.symbols` get substituted into the Gibbs energy expressions when the Model is instantiated. If the Gibbs energy expression uses a symbol that is not defined in the `dbf.symbols`, then that symbol will be left in symbolically and later set to zero implicitly by `calculate` and `equilibrium` (consistent with the behavior of Thermo-Calc). 

The following example illustrates how this works:

```python
# Define a simple TDB string just for convenience
TDB = """
ELEMENT A FCC_A1 0 0 0 !

TYPE_DEFINITION % SEQ * !
DEFINE_SYSTEM_DEFAULT ELEMENT 2 !

PHASE ALPHA %  1 1 !
CONSTITUENT ALPHA :A: !

FUNCTION GHSERA 1 -20000; 10000 N !

PARAMETER G(ALPHA,A;0) 1 GHSERA - 10000 + 3*T; 10000 N !
"""

from pycalphad import Model, Database
dbf = Database(TDB)

print('Current Database symbols', dbf.symbols)

# First make a Model (mod_1) and print the Gibbs energy using the Database as-is
# Observe that the value for the FUNCTION GHSERA was substituted in
mod_1 = Model(dbf, ['A'], 'ALPHA')
print('mod_1.GM for the as-is Database:')
print(mod_1.GM)

# Set the dbf.symbols to an empty dictionary, effectively deleting all symbols
print('Replacing dbf.symbols with an empty dictionary')
dbf.symbols = {}
print('Current Database symbols', dbf.symbols)

# Print the Gibbs energy for mod_1 again, showing the same Gibbs energy
# the symbols are replaced when the model was created and changing the Database after doesn't change the Model
print('mod_1.GM for the Database after deleting the GHSERA function')
print(mod_1.GM)

# Instantiate a new Model (mod_2), which gives the Gibbs energy where the GHSERA function which is not substituted
# since it is not defined in the Database
mod_2 = Model(dbf, ['A'], 'ALPHA')
print('mod_2.GM for the Database after deleting the GHSERA function')
print(mod_2.GM)

```

Running this gives:

```
Current Database symbols {'GHSERA': Piecewise((-20000, (T >= 1.0) & (T < 10000.0)), (0, True))}
mod_1.GM for the as-is Database:
3.0*T + 1.0*Piecewise((-20000, (T >= 1.0) & (T < 10000.0)), (0, True)) - 10000.0 + 8.3145*T*Piecewise((ALPHA0A*log(ALPHA0A), ALPHA0A > 1.0e-16), (0, True))/ALPHA0A
Replacing dbf.symbols with an empty dictionary
Current Database symbols {}
mod_1.GM for the Database after deleting the GHSERA function
3.0*T + 1.0*Piecewise((-20000, (T >= 1.0) & (T < 10000.0)), (0, True)) - 10000.0 + 8.3145*T*Piecewise((ALPHA0A*log(ALPHA0A), ALPHA0A > 1.0e-16), (0, True))/ALPHA0A
mod_2.GM for the Database after deleting the GHSERA function
3.0*T + 1.0*GHSERA - 10000.0 + 8.3145*T*Piecewise((ALPHA0A*log(ALPHA0A), ALPHA0A > 1.0e-16), (0, True))/ALPHA0A
```

`mod_1.GM` includes the value for `GHSERA` substituted in, and the value got substituted in when the Model was instantiated, so the Gibbs energy expression remains the same even after deleting the symbols. However, creating `mod_2` _after_ deleting the symbol results in a Gibbs energy expression `mod_2.GM` that still contains `GHSERA`. Since this symbol is undefined, it will later be set to zero. 

You may be wondering why the undefined symbols are left in the expression from `Model` - the reason is that you can use the `parameters` argument to `calculate` and `equilibrium` to set the values of these symbols (or override already defined ones) at run-time. This is key for doing assessments.

**Comment by Ebert-Daniel** [comment]
I had figured out that I was deleting the value of the symbols, anyways this detailed explanation was very much useful and comprehensive.
 Thank you
