### ISSUE TITLE
unexpected behavior of G^ref when temperature range is set?

### ISSUE THREAD

**Issue by Ebert-Daniel** [pycalphad/pycalphad#307]
Hi all,

When I try to calculate the Gibbs energy of the bcc phase, the Gref seems to not include the Fe end-member if I use parameters with different range of temperature (please see in the tdb file and the commented parameter). 

That is:
if I include G(BCC,Fe:H,0) with different temperature ranges (uncommented parameter), the term representing G(BCC,Fe:VA,0), in this case GHSERFE, does not appear in the final  GM(BCC) function. Is there something I'm not seeing? 

Attached you may find the tdb for running this question using the script below:

_from pycalphad import Model
dbf = Database('bcc.tdb')
comps = ['FE','H','VA']
dbf.symbols = {}
bcc_mod = Model(dbf, ['FE','H','VA'], 'BCC')
bcc_mod.GM_

tdb:
[bcc.txt](https://github.com/pycalphad/pycalphad/files/6061713/bcc.txt)

**Comment by bocklund** [comment]
It looks like `PARAMETER G(BCC,FE:H;0)` (lines 29-31) is not terminated by an `!`. Adding it seems to give the expected behavior.

Specifically, lines 29-31 in the TDB are:


```
     PARAMETER G(BCC,FE:H;0) 298.15  +GHSERFE+1.5*GHSERHH
        +258000-3170*T+498*T*LN(T)-0.275*T**2; 1811.00  Y
        +232264+82*T+1*GHSERFE+1.5*GHSERHH; 6000.00  N 
```

The last line in the parameter (line 31) does not end with a `!`, so I think what's happening is that the TDB parser is considering everything below to be one line

```
     PARAMETER G(BCC,FE:H;0) 298.15  +GHSERFE+1.5*GHSERHH
        +258000-3170*T+498*T*LN(T)-0.275*T**2; 1811.00  Y
        +232264+82*T+1*GHSERFE+1.5*GHSERHH; 6000.00  N  
$     PARAMETER G(BCC,FE:H;0)  298.15 +GHSERFE+1.5*GHSERHH
$     +433143.124-4463.227*T+722.704*T*LN(+T) -0.4090968*T**2; 6000 N KIM !

     PARAMETER G(BCC,FE:VA;0)      298.15 +GHSERFE; 6000 N ZIM !
```

and everything after the `6000.00 N` on line 31 is getting thrown away, including the `PARAMETER G(BCC,FE:VA;0)` parameter which is not in `dbf._parameters.all()`.

It would be nice if our TDB parser could flag this as an error to the user.

**Comment by Ebert-Daniel** [comment]
I just realized the mistake when trying to use other software.

OpenCalphad tells how many parameters were in the model and how many were selected. 
ThermoCalc tells the user that there is an error.

Thanks for helping
