### ISSUE TITLE
Issue displaying energies of phase when it has ordering contribution 

### ISSUE THREAD

**Issue by Ebert-Daniel** [pycalphad/pycalphad#317]
Hello,

I have a problem when trying to display the energy formula of  BCC_B2 phase in Jupyter notebook. It displays in a unformulated text format.

The following code reproduces the error:
```
from pycalphad import Model, Database
mod = Model(Database('al-c-fe.tdb'), ['FE','AL','C','VA'], 'B2_BCC')
mod.GM
```
the database:
[al-c-fe.txt](https://github.com/pycalphad/pycalphad/files/6155689/al-c-fe.txt)

Best regards

**Comment by bocklund** [comment]
@Ebert-Daniel when I ran this, my output looked something like this (as text), where usually it would be the rendered equation:

```
\displaystyle 8.3145 T \left(\frac{0.5 \left(\begin{cases} y^{\mathrm{B2-BCC}}_{0,\mathrm{AL}} \ ...
```

Sometimes the expressions can get really big, especially so for multi-component order-disorder models because of the complexity of the expression. The equation display in Jupyter notebook is handled by SymPy printing the LaTeX that is rendered by the Jupyter notebook. The equation display is not something we have any control over in pycalphad, but maybe there's a SymPy or Jupyter notebook option that can allow for very large expressions.

In the meantime, you can workaround this by printing out the string version of the expression:

```python
str(mod.GM)
```

or, if you want the rendered version, you can try to print out the LaTeX and compile it yourself. I ran:

```python
import sympy
sympy.print_latex(mod.GM)
```

I was able to copy the output over to LaTeXiT and it ran well, but the page sizes probably need to be increased since most of the expression is cut off.

**Comment by bocklund** [comment]
Closing as this seems like an upstream issue in Jupyter displays mostly out of our control. However, it's worth noting that the changes in 0.10.3 due to https://github.com/pycalphad/pycalphad/pull/431 should have improved the situation from pruning the piecewise branches:

```
# 0.10.2
from pycalphad import Model, Database
mod = Model(Database('al-c-fe.txt'), ['FE','AL','C','VA'], 'B2_BCC')
print(len(str(mod.GM)))
# 40953
```

```
# 0.10.3 and current `develop`
from pycalphad import Model, Database
mod = Model(Database('al-c-fe.txt'), ['FE','AL','C','VA'], 'B2_BCC')
print(len(str(mod.GM)))
# 29663
```
