### ISSUE TITLE
Cannot zoom in - ternary phase diagram

### ISSUE THREAD

**Issue by yaomz16** [pycalphad/pycalphad#435]
Hi again :) I was trying to draw a ternary phase diagram with the database I mentioned in #434 (after modification). The drawing is successful, however I cannot zoom in the figure. 
Also, seems like it doesn't work to make the constraint like `v.X('NA'): (0.0,0.05,0.001)`, the generated plot will still be from 0 to 1.

**Comment by yaomz16** [comment]
Also, how do you make the `subplot_kw={'projection': 'triangular'}` possible? I tried only `import matplotlib.pyplot as plt` and then do `fig, (ax) = plt.subplots(subplot_kw={'projection': 'triangular'})`, I got error "ValueError: Unknown projection 'triangular'". However if I import anything about pycalphad (even like `from pycalphad import variables as v`) and do `fig, (ax) = plt.subplots(subplot_kw={'projection': 'triangular'})`, I got an triangle plot

**Comment by bocklund** [comment]
Usually one would change the axis limits, i.e. `ax.set_xlim(0, 0.05)`. I'm not sure if that works for triangular axes and it might be disabled. If you need only a small view like this, I might suggest to use regular Cartesian axes.

The triangular projection is defined inside of pycalphad and registered with matplotlib, which is why you need to import pycalphad for it to work. At the time when we wrote it, we did not find a competing solution that offered plotting and labeling axes in the typical style found in the Calphad community. You can find our implementation here the [pycalphad.plot.triangular module](https://github.com/pycalphad/pycalphad/blob/develop/pycalphad/plot/triangular.py), which is automatically imported when you import pycalphad.

**Comment by richardotis** [comment]
`import pycalphad.plot.triangular` will cause the triangular projection to become available.

**Comment by yaomz16** [comment]
> 

Thanks! That's useful
