### ISSUE TITLE
Error in equilibrium with pycalphad 0.10.2

### ISSUE THREAD

**Issue by tobiasspt** [pycalphad/pycalphad#468]
Hi, 

I do get following error message, when I perform equilibrium calculations at certain conditions with pycalphad 0.10.2. (I have attached the TDB and the example code). 
The error does not occur when I remove GRAPHITE (which contains only 'C' as the component) as a phase. 
The error does occur for similar temperatures and concentrations. 
The error does not occur with pycalphad 0.10.1. 
pycalphad 0.10.1 and ThermoCalc predict, for the same conditions as in the example, a mixture of BCC_A2 and GRAPHITE. 
(['BCC_A2', 'GRAPHITE', '']   [9.99647257e-01, 3.52743135e-04,            nan])

``` 
Traceback (most recent call last):   
    File "C:\Users\spitaler.t\Desktop\example\example.py", line 25, in <module>    
       eq = equilibrium(dbf, ['FE','C','VA'], phases, {v.N:1, v.P:1e5, v.T:T, v.X('C'):0.0053})    
   File "C:\Users\spitaler.t\Miniconda3\envs\ptest2\lib\site-packages\pycalphad\core\equilibrium.py", line 281, in equilibrium   
       properties = _solve_eq_at_conditions(properties, phase_records, grid,            
   File "pycalphad/core/eqsolver.pyx", line 260, in pycalphad.core.eqsolver._solve_eq_at_conditions       
ValueError: could not broadcast input array from shape (4,) into shape (3,)         
```                
[example.zip](https://github.com/pycalphad/pycalphad/files/11219840/example.zip)

How can I avoid this error?

Cheers, 
Tobias

**Comment by richardotis** [comment]
I'm able to reproduce this error, which is a bug. What's happening is that the minimizer is returning a non-physical solution of four stable phases, when only two are allowed by the Gibbs phase rule for the given conditions. (pycalphad will tolerate one extra stable phase (which is where the `3` comes from), to catch invariant reactions.)

The change in behavior is (probably) because of the bugfix in https://github.com/pycalphad/pycalphad/pull/428 which is causing the minimizer to return a different starting point than in 0.10.1. That fix has apparently uncovered another bug here. It should be impossible for the minimizer to return a solution that violates the Gibbs phase rule. I'm investigating it now.

**Comment by richardotis** [comment]
As a workaround, you can try altering the sampling point density:
`eq = equilibrium(dbf, ['FE','C','VA'], phases, {v.N:1, v.P:1e5, v.T:T, v.X('C'):0.0053}, verbose=True, calc_opts={'pdens': 500})`

**Comment by richardotis** [comment]
@tobiasspt I've put together a solution to fix this issue in the minimizer. Is it alright to put the example TDB into the test suite so we can ensure this bug stays fixed?

**Comment by tobiasspt** [comment]
Hi @richardotis,

Thanks for having a look at this issue!
Yes sure, you can use the TDB in your test suite. (Just be aware that the current parameters are not the 'correct' ones to give the correct phase boundaries of the Fe-C system.)

Cheers, 
Tobias
