### ISSUE TITLE
Use nose-timer to calculate timings in the test suite and save results to the website branch

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#49]
As per offline discussion, the `ci/deploy.sh` script should copy the files rendered by `asv publish` in `.asv/html` to a directory in the GitHub pages branch. This should occur for every commit because the benchmark files could be updated with any commit and are not necessarily bound to a specific type of commit.

**Comment by richardotis** [comment]
I think we could probably run the benchmark suite every commit now and regenerate the benchmark graphics along with the doc build/deployment. What do you think?

**Comment by bocklund** [comment]
I think asv is still broken because pycalphad is not pip installable without requirements (see #58). I was thinking about this when looking at issues yesterday and I was leaning towards proposing to drop asv benchmarking.

**Comment by richardotis** [comment]
What if we use the nose-timer plugin to generate timings for the tests (we could add the benchmarks)? How hard would it be to generate the visualizations?

**Comment by bocklund** [comment]
If we were going to do that, why not write a small timeit script to run in CI and run it on a couple of the interesting test cases?

**Comment by richardotis** [comment]
That's what I was thinking, yeah.

On Apr 1, 2017 9:07 PM, Brandon Bocklund <notifications@github.com> wrote:

If we were going to do that, why not write a small timeit script to run in CI and run it on a couple of the interesting test cases?

**Comment by richardotis** [comment]
My thinking on using nose-timer is because it already has a feature for [exporting the results to JSON](https://github.com/mahmoudimus/nose-timer/#how-do-i-export-the-results-). It would be pretty easy to filter the JSON by test key (say, `key.startswith('bench')`) and append the results to a file during the docbuild. Then the results could be rendered as an image or interactive JS graph, or something else.

**Comment by bocklund** [comment]
So something like:

1. nose-timer to a temporary JSON file

2. Switch to website branch

the next few steps in a Python script:

3. read the temporary JSON file, add the commit number (and any other metadata for that datapoint)
4. read existing JSON file with all the previous data from website branch and append new data
5. plot and save figures to docs folder
6. write out the JSON file with all the data 

finally,

7. git add the JSON
8. build docs
9. commit to web branch

or skip step 5 and go the JS route

**Comment by richardotis** [comment]
I think that's a good approach. I would go the matplotlib figure route for now and worry about interactive JS later; since we retain the benchmarking data in JSON.

I might add the pycalphad-base Docker image ID along with the commit ID to the metadata. It's not so useful at the moment, but if we started archiving all the base images, we might be able to debug strange performance regressions due to dependency updates.

**Comment by bocklund** [comment]
Maybe also do a timeit of something of something in the standard library or something we can do off of a base install of pycalphad and record that time so we can compare the relative times across hardware.

**Comment by bocklund** [comment]
As time has gone by, we haven't really paid much attention to the test suite times other than watching them balloon during major architecture changes. Anyways, the majority of the timings are more of a reflection of the amount of cases that call out to the compiler, which doesn't really represent very realistic scenarios for finding regressions that were are able to control.

That being the case, I think it makes sense to close this.
