### ISSUE TITLE
Plotting arbitrary isopleths

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#5]
Users would have a plot() style interface for specifying arbitrary sections through composition space. This is not too conceptually difficult using the energy_surf routine and scipy's ConvexHull routine (though we may run into performance problems); the main trick is efficiently calculating intersections of hyperplanes with the convex hull. Routines exist for this but need to be investigated further.

**Comment by richardotis** [comment]
The `lower_convex_hull` routine in the geometry module is performant enough to take this task on now. There's probably a way to vectorize it so that it can accept an ndarray of conditions and return EquilibriumResult objects in the same shape. Another issue is making sure we have a reliable answer so we don't end up with answers dependent on the initial point density, since right now `lower_convex_hull` is mostly used for finding starting points.

**Comment by richardotis** [comment]
It looks like `equilibrium` could probably do this task now with some tweaking, so I'll put it on the roadmap for 0.4.

**Comment by bocklund** [comment]
#98

**Comment by richardotis** [comment]
@bocklund Confused why this issue is tagged. Are you saying that PR lets you plot isopleths (slices through composition space as a function of T)?

**Comment by bocklund** [comment]
Brain malfunction

**Comment by bocklund** [comment]
Although I think my changes could be progress towards handling this nicely if I can figure out how to concatenate all of the points together for n-phase regions. We could just do a Gibbs phase rule calculations to calculate `p` and loop over the indices search, plotting, and tielines from 2 to `p` phases. It would use all of the same logic I already have, but instead of plotting `x[.., 0], y[..., 0]`, `x[.., 1], y[..., 1]` we just concatenate the last dimension and plot/construct tielines with that one array.

**Comment by richardotis** [comment]
In principle it's a straightforward implementation if you are okay with just plotting the tie-line points at each temperature. The key is the math for projecting the high-dimensional tie-plane onto the isopleth compositional line.

**Comment by richardotis** [comment]
An attempt at the geometry: create a triangle where one vertex (A) is the origin of the isopleth line, the second vertex (B) is the tie-plane point of interest (in high-dimensional space), and the third vertex (C) is the unknown point along the isopleth line.

We know:
- Length of side AB: we know coordinates of both A and B
- Angle ACB: must be 90 degrees, by construction
- Length of side BC: we can compute this from the [hyperplane distance formula](https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_plane)

Solve for:
- Length of side AC

Solution:
- First, solve for angle BAC: `arcsin(BC/AB)`
- Next, solve for length AC: `BC/tan(BAC)` = `BC/tan(arcsin(BC/AB))`

Once AC is known, we can use the equation for this isopleth line to map point A to a point on the line.

**Comment by bocklund** [comment]
> The key is the math for projecting the high-dimensional tie-plane onto the isopleth compositional line.

What does this mean? Are you talking about plotting the actual tielines themselves or the endpoints (ZPF lines)?

**Comment by richardotis** [comment]
ZPF lines.

**Comment by bocklund** [comment]
> In principle it's a straightforward implementation if you are okay with just plotting the tie-line points at each temperature. The key is the math for projecting the high-dimensional tie-plane onto the isopleth compositional line.

> An attempt at the geometry: create a triangle where one vertex (A) is the origin of the isopleth line, the second vertex (B) is the tie-plane point of interest (in high-dimensional space), and the third vertex (C) is the unknown point along the isopleth line.
> 
> We know:
> 
>     * Length of side AB: we know coordinates of both A and B
> 
>     * Angle ACB: must be 90 degrees, by construction
> 
>     * Length of side BC: we can compute this from the [hyperplane distance formula](https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_plane)
> 
> 
> Solve for:
> 
>     * Length of side AC
> 
> 
> Solution:
> 
>     * First, solve for angle BAC: `arcsin(BC/AB)`
> 
>     * Next, solve for length AC: `BC/tan(BAC)` = `BC/tan(arcsin(BC/AB))`
> 
> 
> Once AC is known, we can use the equation for this isopleth line to map point A to a point on the line.


I think we've changed our thinking on this, but I wanted to document that here. The approach outlined here to compute the ZPF line by finding the intersection between an equilibrium hyperplane and the line of the isopleth won't work because the intersection of a hyperplane and the isopleth line doesn't correspond to a change in the set of phases --- a point on a zero phase fraction line. 

The key is that, within the plane of the diagram, one needs to know when there is a change in the stable set of phases, and this by definition, marks a point on the diagram where one phase has zero phase amount (the phase that either appears or disappears). This applies to any mapped axis, e.g. temperature or composition or chemical potential, etc.

Using the fixed phase condition to follow the lines where a phase has zero amount is the most widely accepted way of doing this and it's now theoretically possible to do these calculations using the new minimizer from #329. Thus, the main outstanding issues for isopleth plotting are:

*  To develop a general algorithm to follow zero phase fraction lines from starting points for any desired axis variable. The algorithm needs to
  * generate starting points (and/or be given start points from a user)
  * follow a zero phase fraction line until the set of phases changes (changing the conditions to compute an invariant reaction, if there is one) and generate new starting points
  * store and plot the data
* To expose a mechanism for defining the relationship between conditions in an isopleth, for example a relationship between composition conditions.
  * One option could be to support giving fixed arrays of matching conditions, for example in a 4 component T-X isopleth, explicitly providing a list of 100 compositions along the diagram for three independent components that are _not_ broadcast against each other. This may be the easiest to get working for T-X isopleths, but may not generalize to other conditions very easily.
  * Another is to add support in the minimizer for linear relationships between conditions, e.g. `a*v.X('NI') + b*v.('CR') = c` for given constants `a`, `b` and `c`. It should be possible to handle these entirely in the minimizer by making linear combinations of rows in the equilibrium matrix.

**Comment by bocklund** [comment]
We now have initial isopleth support from #543, documented here: https://pycalphad.org/docs/latest/examples/Mapping.html#Isopleth-plotting
