### ISSUE TITLE
Warn user when specifying invalid kwargs to equilibrium and calculate

### ISSUE THREAD

**Issue by richardotis** [pycalphad/pycalphad#52]
Example: when specifying raw pdens as kwarg to equilibrium() -- this is incorrect

**Comment by bocklund** [comment]
Can we just add a check that `if len(kwargs) != 0: warn and print(kwargs)` to the end of equilibrium (and calculate, etc.)? The idea being since we use kwargs.pop() to get our kwargs, ideally kwargs is empty at the end of the function since we've popped everything we want and if len(kwargs) is non-zero that means we passed some kwarg that did not get used.

One downside, besides being messy, is that kwargs in branch logic that don't get popped would raise warnings. Not sure where/if that would happen. 

It seems like someone else should've solved this problem nicely, but I'm not using the right search terms for it.

**Comment by richardotis** [comment]
Your solution sounds fine.

**Comment by bocklund** [comment]
Which functions? equilibrium and calculate? Since those are the ones that would affect the intended calculation. Anywhere else?

**Comment by richardotis** [comment]
I'm inclined to say just equilibrium and calculate since the API for other pycalphad objects isn't too complicated. One issue is that this is liable to cause forward and backward compatibility issues as kwargs appear and disappear from the API.

**Comment by bocklund** [comment]
Regarding compatibility: that's what we want right? You don't want equilibrium/calculate to eat some outdated API and not give the intended result.

**Comment by richardotis** [comment]
It's arguable for cosmetic things like the old `pbar` kwarg for the equilibrium progress bar.

**Comment by bocklund** [comment]
calculate tries to convert remaining kwargs into StateVariables, so passing invalid kwargs to calculate is actually not possible without raising an exception (line 415 in calculate.py).

**Comment by richardotis** [comment]
Just handling the case for equilibrium should be fine then.
