### ISSUE TITLE
Order-disorder transition lines

### ISSUE THREAD

**Issue by xuanliu1986** [pycalphad/pycalphad#7]
Hi Richard, it would be good to implement a order-disorder transition plotting tool that would look at the differences in the site fractions. For example in a 2 sublattice BCC_B2, model, it would calculate when x(comp1) in site 1 is different from x(comp 1) in site 2. This has to be done manually in Thermo-Calc right now and sometimes it does not work correctly without trying many compositions first.

**Comment by richardotis** [comment]
I received another question about this at the CALPHAD meeting. I'd mostly been thinking this would be pretty difficult to implement for general second-order transitions, but I now think I have a solution for atomic ordering. In the plotting code we normally define the tie-line for a miscibility gap based on the RMS distance between the two points in composition space. Once that distance is "significantly" greater than the density of our grid, we assume it's a tie-line instead of a single-phase region.

For atomic ordering defining the transitions is a little more complicated. What we can do is define a "degree of ordering" for each point on the candidate tie-line as the magnitude of the difference between the overall composition and the constitution of each sublattice. Each sublattice has a "degree of ordering" calculated such that a transition boundary can be defined as anywhere the magnitude of the difference of degrees-of-ordering vectors is "large".

Magnetic transitions are easy: Compute TC where the phase is stable, and where TC approaches T draw a boundary.

**Comment by richardotis** [comment]
Or am I thinking about this incorrectly, and I should be looking at the mixed second-derivatives of the site fractions with temperature?

**Comment by richardotis** [comment]
So `equilibrium` can reasonably minimize internal degrees of freedom in step/map calculations now, so in principle this is pretty easy to implement:
- At some T_i and x, compute the degree of ordering and compare to the same at T_{i+1}
- When the degree of ordering change is "large", set T_ord = (T_i + T_{i+1}) / 2
- Draw T_ord for all x where the given phase of interest is stable

I'll put this on the roadmap for 0.4.

**Comment by richardotis** [comment]
With the new `degree_of_ordering` and `curie_temperature` properties implemented, writing code to overplot these transition lines should be pretty straightforward.

**Comment by richardotis** [comment]
I made a first attempt at this, which you can find in the sandbox: https://github.com/pycalphad/pycalphad/blob/356b12422bbfe191deb3a902e10088aa47c4afd9/research/ContourMap.ipynb

The result, which shows lines of constant `degree_of_ordering` in solid black and the magnetic transition temperature on the grey fashed line, looks pretty good.

![image](https://cloud.githubusercontent.com/assets/6405510/13149431/81c17460-d62f-11e5-8f36-f2685082b990.png)
