### ISSUE TITLE
Use better colors in phase_legend()

### ISSUE THREAD

**Issue by bocklund** [pycalphad/pycalphad#97]
The colors generated here are ok for the initial ones in the list in `phase legend`, but later ones are not appealing and hard to discern. Roughly half of the colors in the image are very hard to discern. 

The code to generate colors originally came from http://junweihuang.info/uncategorized/automatically-generate-n-distinct-colors-a-python-script/

But there might be better ways in the [original SO discussion](https://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors) where we can try to better generate ~50 default colors (currently we are using 54). 

![Sample of colors](https://cloud.githubusercontent.com/assets/7681751/26807735/1386dc30-4a0d-11e7-8d05-ff7d87f8c9d7.png)

**Comment by bocklund** [comment]
The steps to accomplish this would simply be to 

1. Use one of the solutions in the [SO answers] (https://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors) and generate a better list of colors (or just take an existing list of colors)
2. replace the list of color values of the `phase_legend` function in `pycalphad.plot.utils`

**Comment by Cactusmachete** [comment]
Hey!
I'm new here, but noticed that this issue is labelled beginner. Is it alright if I try and resolve this issue?

**Comment by richardotis** [comment]
@Cactusmachete Welcome. Yes, you can work on resolving this issue.

**Comment by bocklund** [comment]
Hi @Cactusmachete, have you made any progress addressing this? Feel free to let us know if you have any questions!

**Comment by HUI1SUN** [comment]
There is a paper named A Colour Alphabet and the Limits of Colour Coding in web(https//www.researchgate.net/publication/237005166_A_Colour_Alphabet_and_the_Limits_of_Colour_Coding), which mentioned Kelly's 22 colors of maximum contrast. I'm trying to generate a new color list based on it, hoping to get a better list of colors.

**Comment by richardotis** [comment]
@HUI1SUN In what order should the colors be used?

**Comment by HUI1SUN** [comment]
@richardotis I'm thinking that put the order in this way. First, putting all the Kelly's colors in the front of the order, since these colors are most distinctive. Then, ranking the rest color according to their hue. And, there is the picture of ordered colors.
![figure_1](https://user-images.githubusercontent.com/37977573/43776018-3129e816-9a81-11e8-8d79-39e79b03313c.png)

**Comment by richardotis** [comment]
Great. Could you put your proposed ordering in a Python list for us to copy and paste, or write a pull request with your changes?

**Comment by bocklund** [comment]
In my opinion, we should try to order them so that the color `i+1` is the furthest (most distinctive) from colors `0:i`. That is a simple way to get near the optimal amount of color separation for any number of phases.

This is definitely a harder problem than I originally thought, but the colors you provided, @HUI1SUN, look much much better than the example in the original comment.

**Comment by igorjrd** [comment]
I noticed that this topic is not active by more than 1 year and considerable advance about the solution of this issue was developed previously, so I decided to help finishing the solution of this issue. To follow the suggestion of @bocklund about ordering the colors by its distinctivy considering, I developed a little script that takes a list of colors and reorders it in an order that the `i+1` color is the most distinct color compared to the last 'N' colors. Inittially, I observed that considering just the color `i-1` to select the color `i` results in a color pallete that presents the color `i+2` considerably similar to the color `i`. The figure below shows this behavior (the colors are ordered descending):

![pallete1](https://user-images.githubusercontent.com/52574978/65819843-cc2a3280-e1f7-11e9-939e-439094d78d9f.png)

To avoid this behavior, I developed the algorithm to take the previous N colors in consideration to select the next color. By this means, I obtained the following order:

![pallete](https://user-images.githubusercontent.com/52574978/65819853-e106c600-e1f7-11e9-9ce0-0e4e5459918c.png)

To quantify the distinctability between two colors I used the CIEDE 2000 formula: https://en.wikipedia.org/wiki/Color_difference#CIEDE2000

**Comment by bocklund** [comment]
Are the colors top-to-bottom then left-to-right or left-to-right then top-to-bottom? If it's top-to-bottom, then left-to-right (i.e. the entire left column comes first: #00538a followed by #f4c800 and #f13a13 ...), I personally find that very pleasing. I'd be happy to review and merge a PR containing that order of colors.

It's kind of interesting that the browns tend to all show up at the end. I think it's probably because brown is in the middle and not markedly distinct from anything, so they all get pushed down to the end of the list.

**Comment by igorjrd** [comment]
@bocklund, the colors are top-to-bottom then left to right. I think that brownish colors maybe presents lower values of distinctivity compared to other colors. I can try to use the algorithm that i wrote to build an order using another pallete, if you think that it would be interesting. The pallete that I used to build this order was the pallete proposed previously by HUI1SUN.
